//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ConsoleApplication1.Orcl_ldbs3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Orcl_Idbs3Soap", Namespace="http://tempuri.org/")]
    public partial class Orcl_Idbs3 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDtTableXYOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDtSTCD8OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSQStcdTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHDSWXTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback DBODSWX_XY_DtOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDtYQOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYQStcdTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback DZX_DtOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetliuyujyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetliuliangOperationCompleted;
        
        private System.Threading.SendOrPostCallback fx_liuyucj_sdstateOperationCompleted;
        
        private System.Threading.SendOrPostCallback fx_liuyucj_sdmaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback fx_liuyucj_stateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ToStrongOperationCompleted;
        
        private System.Threading.SendOrPostCallback fx_liuyujyOperationCompleted;
        
        private System.Threading.SendOrPostCallback fx_fenquOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Orcl_Idbs3() {
            this.Url = global::ConsoleApplication1.Properties.Settings.Default.ConsoleApplication1_Orcl_ldbs3_Orcl_Idbs3;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetDtTableXYCompletedEventHandler GetDtTableXYCompleted;
        
        /// <remarks/>
        public event GetDtSTCD8CompletedEventHandler GetDtSTCD8Completed;
        
        /// <remarks/>
        public event GetSQStcdTableCompletedEventHandler GetSQStcdTableCompleted;
        
        /// <remarks/>
        public event GetHDSWXTableCompletedEventHandler GetHDSWXTableCompleted;
        
        /// <remarks/>
        public event DBODSWX_XY_DtCompletedEventHandler DBODSWX_XY_DtCompleted;
        
        /// <remarks/>
        public event GetDtYQCompletedEventHandler GetDtYQCompleted;
        
        /// <remarks/>
        public event GetYQStcdTableCompletedEventHandler GetYQStcdTableCompleted;
        
        /// <remarks/>
        public event DZX_DtCompletedEventHandler DZX_DtCompleted;
        
        /// <remarks/>
        public event GetliuyujyCompletedEventHandler GetliuyujyCompleted;
        
        /// <remarks/>
        public event GetliuliangCompletedEventHandler GetliuliangCompleted;
        
        /// <remarks/>
        public event fx_liuyucj_sdstateCompletedEventHandler fx_liuyucj_sdstateCompleted;
        
        /// <remarks/>
        public event fx_liuyucj_sdmaxCompletedEventHandler fx_liuyucj_sdmaxCompleted;
        
        /// <remarks/>
        public event fx_liuyucj_stateCompletedEventHandler fx_liuyucj_stateCompleted;
        
        /// <remarks/>
        public event ToStrongCompletedEventHandler ToStrongCompleted;
        
        /// <remarks/>
        public event fx_liuyujyCompletedEventHandler fx_liuyujyCompleted;
        
        /// <remarks/>
        public event fx_fenquCompletedEventHandler fx_fenquCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDtTableXY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDtTableXY(string a, string b, string c, string d, string e, string f) {
            object[] results = this.Invoke("GetDtTableXY", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDtTableXYAsync(string a, string b, string c, string d, string e, string f) {
            this.GetDtTableXYAsync(a, b, c, d, e, f, null);
        }
        
        /// <remarks/>
        public void GetDtTableXYAsync(string a, string b, string c, string d, string e, string f, object userState) {
            if ((this.GetDtTableXYOperationCompleted == null)) {
                this.GetDtTableXYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDtTableXYOperationCompleted);
            }
            this.InvokeAsync("GetDtTableXY", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f}, this.GetDtTableXYOperationCompleted, userState);
        }
        
        private void OnGetDtTableXYOperationCompleted(object arg) {
            if ((this.GetDtTableXYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDtTableXYCompleted(this, new GetDtTableXYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDtSTCD8", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDtSTCD8(string a) {
            object[] results = this.Invoke("GetDtSTCD8", new object[] {
                        a});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDtSTCD8Async(string a) {
            this.GetDtSTCD8Async(a, null);
        }
        
        /// <remarks/>
        public void GetDtSTCD8Async(string a, object userState) {
            if ((this.GetDtSTCD8OperationCompleted == null)) {
                this.GetDtSTCD8OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDtSTCD8OperationCompleted);
            }
            this.InvokeAsync("GetDtSTCD8", new object[] {
                        a}, this.GetDtSTCD8OperationCompleted, userState);
        }
        
        private void OnGetDtSTCD8OperationCompleted(object arg) {
            if ((this.GetDtSTCD8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDtSTCD8Completed(this, new GetDtSTCD8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSQStcdTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSQStcdTable(string a, string b, string c) {
            object[] results = this.Invoke("GetSQStcdTable", new object[] {
                        a,
                        b,
                        c});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSQStcdTableAsync(string a, string b, string c) {
            this.GetSQStcdTableAsync(a, b, c, null);
        }
        
        /// <remarks/>
        public void GetSQStcdTableAsync(string a, string b, string c, object userState) {
            if ((this.GetSQStcdTableOperationCompleted == null)) {
                this.GetSQStcdTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSQStcdTableOperationCompleted);
            }
            this.InvokeAsync("GetSQStcdTable", new object[] {
                        a,
                        b,
                        c}, this.GetSQStcdTableOperationCompleted, userState);
        }
        
        private void OnGetSQStcdTableOperationCompleted(object arg) {
            if ((this.GetSQStcdTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSQStcdTableCompleted(this, new GetSQStcdTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHDSWXTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHDSWXTable(string a, string b, string c) {
            object[] results = this.Invoke("GetHDSWXTable", new object[] {
                        a,
                        b,
                        c});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHDSWXTableAsync(string a, string b, string c) {
            this.GetHDSWXTableAsync(a, b, c, null);
        }
        
        /// <remarks/>
        public void GetHDSWXTableAsync(string a, string b, string c, object userState) {
            if ((this.GetHDSWXTableOperationCompleted == null)) {
                this.GetHDSWXTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHDSWXTableOperationCompleted);
            }
            this.InvokeAsync("GetHDSWXTable", new object[] {
                        a,
                        b,
                        c}, this.GetHDSWXTableOperationCompleted, userState);
        }
        
        private void OnGetHDSWXTableOperationCompleted(object arg) {
            if ((this.GetHDSWXTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHDSWXTableCompleted(this, new GetHDSWXTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DBODSWX_XY_Dt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DBODSWX_XY_Dt(string a, string b, string c, string d, string e, string f) {
            object[] results = this.Invoke("DBODSWX_XY_Dt", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DBODSWX_XY_DtAsync(string a, string b, string c, string d, string e, string f) {
            this.DBODSWX_XY_DtAsync(a, b, c, d, e, f, null);
        }
        
        /// <remarks/>
        public void DBODSWX_XY_DtAsync(string a, string b, string c, string d, string e, string f, object userState) {
            if ((this.DBODSWX_XY_DtOperationCompleted == null)) {
                this.DBODSWX_XY_DtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDBODSWX_XY_DtOperationCompleted);
            }
            this.InvokeAsync("DBODSWX_XY_Dt", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f}, this.DBODSWX_XY_DtOperationCompleted, userState);
        }
        
        private void OnDBODSWX_XY_DtOperationCompleted(object arg) {
            if ((this.DBODSWX_XY_DtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DBODSWX_XY_DtCompleted(this, new DBODSWX_XY_DtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDtYQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDtYQ(string a, string b, string c, string d, string e, string f, string g) {
            object[] results = this.Invoke("GetDtYQ", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f,
                        g});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDtYQAsync(string a, string b, string c, string d, string e, string f, string g) {
            this.GetDtYQAsync(a, b, c, d, e, f, g, null);
        }
        
        /// <remarks/>
        public void GetDtYQAsync(string a, string b, string c, string d, string e, string f, string g, object userState) {
            if ((this.GetDtYQOperationCompleted == null)) {
                this.GetDtYQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDtYQOperationCompleted);
            }
            this.InvokeAsync("GetDtYQ", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f,
                        g}, this.GetDtYQOperationCompleted, userState);
        }
        
        private void OnGetDtYQOperationCompleted(object arg) {
            if ((this.GetDtYQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDtYQCompleted(this, new GetDtYQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetYQStcdTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetYQStcdTable(string a, string b, string c) {
            object[] results = this.Invoke("GetYQStcdTable", new object[] {
                        a,
                        b,
                        c});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetYQStcdTableAsync(string a, string b, string c) {
            this.GetYQStcdTableAsync(a, b, c, null);
        }
        
        /// <remarks/>
        public void GetYQStcdTableAsync(string a, string b, string c, object userState) {
            if ((this.GetYQStcdTableOperationCompleted == null)) {
                this.GetYQStcdTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYQStcdTableOperationCompleted);
            }
            this.InvokeAsync("GetYQStcdTable", new object[] {
                        a,
                        b,
                        c}, this.GetYQStcdTableOperationCompleted, userState);
        }
        
        private void OnGetYQStcdTableOperationCompleted(object arg) {
            if ((this.GetYQStcdTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYQStcdTableCompleted(this, new GetYQStcdTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DZX_Dt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DZX_Dt(string a, string b, string c, string d, string e) {
            object[] results = this.Invoke("DZX_Dt", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DZX_DtAsync(string a, string b, string c, string d, string e) {
            this.DZX_DtAsync(a, b, c, d, e, null);
        }
        
        /// <remarks/>
        public void DZX_DtAsync(string a, string b, string c, string d, string e, object userState) {
            if ((this.DZX_DtOperationCompleted == null)) {
                this.DZX_DtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDZX_DtOperationCompleted);
            }
            this.InvokeAsync("DZX_Dt", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e}, this.DZX_DtOperationCompleted, userState);
        }
        
        private void OnDZX_DtOperationCompleted(object arg) {
            if ((this.DZX_DtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DZX_DtCompleted(this, new DZX_DtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getliuyujy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Getliuyujy(string a, string b, string c) {
            object[] results = this.Invoke("Getliuyujy", new object[] {
                        a,
                        b,
                        c});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetliuyujyAsync(string a, string b, string c) {
            this.GetliuyujyAsync(a, b, c, null);
        }
        
        /// <remarks/>
        public void GetliuyujyAsync(string a, string b, string c, object userState) {
            if ((this.GetliuyujyOperationCompleted == null)) {
                this.GetliuyujyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetliuyujyOperationCompleted);
            }
            this.InvokeAsync("Getliuyujy", new object[] {
                        a,
                        b,
                        c}, this.GetliuyujyOperationCompleted, userState);
        }
        
        private void OnGetliuyujyOperationCompleted(object arg) {
            if ((this.GetliuyujyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetliuyujyCompleted(this, new GetliuyujyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getliuliang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Getliuliang(string a, string b, string c, string d) {
            object[] results = this.Invoke("Getliuliang", new object[] {
                        a,
                        b,
                        c,
                        d});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetliuliangAsync(string a, string b, string c, string d) {
            this.GetliuliangAsync(a, b, c, d, null);
        }
        
        /// <remarks/>
        public void GetliuliangAsync(string a, string b, string c, string d, object userState) {
            if ((this.GetliuliangOperationCompleted == null)) {
                this.GetliuliangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetliuliangOperationCompleted);
            }
            this.InvokeAsync("Getliuliang", new object[] {
                        a,
                        b,
                        c,
                        d}, this.GetliuliangOperationCompleted, userState);
        }
        
        private void OnGetliuliangOperationCompleted(object arg) {
            if ((this.GetliuliangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetliuliangCompleted(this, new GetliuliangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fx_liuyucj_sdstate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fx_liuyucj_sdstate(string a, string b, string c, string d) {
            object[] results = this.Invoke("fx_liuyucj_sdstate", new object[] {
                        a,
                        b,
                        c,
                        d});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fx_liuyucj_sdstateAsync(string a, string b, string c, string d) {
            this.fx_liuyucj_sdstateAsync(a, b, c, d, null);
        }
        
        /// <remarks/>
        public void fx_liuyucj_sdstateAsync(string a, string b, string c, string d, object userState) {
            if ((this.fx_liuyucj_sdstateOperationCompleted == null)) {
                this.fx_liuyucj_sdstateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfx_liuyucj_sdstateOperationCompleted);
            }
            this.InvokeAsync("fx_liuyucj_sdstate", new object[] {
                        a,
                        b,
                        c,
                        d}, this.fx_liuyucj_sdstateOperationCompleted, userState);
        }
        
        private void Onfx_liuyucj_sdstateOperationCompleted(object arg) {
            if ((this.fx_liuyucj_sdstateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fx_liuyucj_sdstateCompleted(this, new fx_liuyucj_sdstateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fx_liuyucj_sdmax", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fx_liuyucj_sdmax(string a, string b, string c, string d) {
            object[] results = this.Invoke("fx_liuyucj_sdmax", new object[] {
                        a,
                        b,
                        c,
                        d});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fx_liuyucj_sdmaxAsync(string a, string b, string c, string d) {
            this.fx_liuyucj_sdmaxAsync(a, b, c, d, null);
        }
        
        /// <remarks/>
        public void fx_liuyucj_sdmaxAsync(string a, string b, string c, string d, object userState) {
            if ((this.fx_liuyucj_sdmaxOperationCompleted == null)) {
                this.fx_liuyucj_sdmaxOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfx_liuyucj_sdmaxOperationCompleted);
            }
            this.InvokeAsync("fx_liuyucj_sdmax", new object[] {
                        a,
                        b,
                        c,
                        d}, this.fx_liuyucj_sdmaxOperationCompleted, userState);
        }
        
        private void Onfx_liuyucj_sdmaxOperationCompleted(object arg) {
            if ((this.fx_liuyucj_sdmaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fx_liuyucj_sdmaxCompleted(this, new fx_liuyucj_sdmaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fx_liuyucj_state", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fx_liuyucj_state(string a, string b, string c, string d) {
            object[] results = this.Invoke("fx_liuyucj_state", new object[] {
                        a,
                        b,
                        c,
                        d});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fx_liuyucj_stateAsync(string a, string b, string c, string d) {
            this.fx_liuyucj_stateAsync(a, b, c, d, null);
        }
        
        /// <remarks/>
        public void fx_liuyucj_stateAsync(string a, string b, string c, string d, object userState) {
            if ((this.fx_liuyucj_stateOperationCompleted == null)) {
                this.fx_liuyucj_stateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfx_liuyucj_stateOperationCompleted);
            }
            this.InvokeAsync("fx_liuyucj_state", new object[] {
                        a,
                        b,
                        c,
                        d}, this.fx_liuyucj_stateOperationCompleted, userState);
        }
        
        private void Onfx_liuyucj_stateOperationCompleted(object arg) {
            if ((this.fx_liuyucj_stateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fx_liuyucj_stateCompleted(this, new fx_liuyucj_stateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ToStrong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ToStrong(string a, int b) {
            object[] results = this.Invoke("ToStrong", new object[] {
                        a,
                        b});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ToStrongAsync(string a, int b) {
            this.ToStrongAsync(a, b, null);
        }
        
        /// <remarks/>
        public void ToStrongAsync(string a, int b, object userState) {
            if ((this.ToStrongOperationCompleted == null)) {
                this.ToStrongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnToStrongOperationCompleted);
            }
            this.InvokeAsync("ToStrong", new object[] {
                        a,
                        b}, this.ToStrongOperationCompleted, userState);
        }
        
        private void OnToStrongOperationCompleted(object arg) {
            if ((this.ToStrongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ToStrongCompleted(this, new ToStrongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fx_liuyujy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fx_liuyujy(string a, string b, string c, string d, string e, string f) {
            object[] results = this.Invoke("fx_liuyujy", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fx_liuyujyAsync(string a, string b, string c, string d, string e, string f) {
            this.fx_liuyujyAsync(a, b, c, d, e, f, null);
        }
        
        /// <remarks/>
        public void fx_liuyujyAsync(string a, string b, string c, string d, string e, string f, object userState) {
            if ((this.fx_liuyujyOperationCompleted == null)) {
                this.fx_liuyujyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfx_liuyujyOperationCompleted);
            }
            this.InvokeAsync("fx_liuyujy", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f}, this.fx_liuyujyOperationCompleted, userState);
        }
        
        private void Onfx_liuyujyOperationCompleted(object arg) {
            if ((this.fx_liuyujyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fx_liuyujyCompleted(this, new fx_liuyujyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fx_fenqu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fx_fenqu(string a, string b, string c, string d, string e, string f) {
            object[] results = this.Invoke("fx_fenqu", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void fx_fenquAsync(string a, string b, string c, string d, string e, string f) {
            this.fx_fenquAsync(a, b, c, d, e, f, null);
        }
        
        /// <remarks/>
        public void fx_fenquAsync(string a, string b, string c, string d, string e, string f, object userState) {
            if ((this.fx_fenquOperationCompleted == null)) {
                this.fx_fenquOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfx_fenquOperationCompleted);
            }
            this.InvokeAsync("fx_fenqu", new object[] {
                        a,
                        b,
                        c,
                        d,
                        e,
                        f}, this.fx_fenquOperationCompleted, userState);
        }
        
        private void Onfx_fenquOperationCompleted(object arg) {
            if ((this.fx_fenquCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fx_fenquCompleted(this, new fx_fenquCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetDtTableXYCompletedEventHandler(object sender, GetDtTableXYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDtTableXYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDtTableXYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetDtSTCD8CompletedEventHandler(object sender, GetDtSTCD8CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDtSTCD8CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDtSTCD8CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSQStcdTableCompletedEventHandler(object sender, GetSQStcdTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSQStcdTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSQStcdTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetHDSWXTableCompletedEventHandler(object sender, GetHDSWXTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHDSWXTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHDSWXTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DBODSWX_XY_DtCompletedEventHandler(object sender, DBODSWX_XY_DtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DBODSWX_XY_DtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DBODSWX_XY_DtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetDtYQCompletedEventHandler(object sender, GetDtYQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDtYQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDtYQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetYQStcdTableCompletedEventHandler(object sender, GetYQStcdTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYQStcdTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYQStcdTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DZX_DtCompletedEventHandler(object sender, DZX_DtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DZX_DtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DZX_DtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetliuyujyCompletedEventHandler(object sender, GetliuyujyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetliuyujyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetliuyujyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetliuliangCompletedEventHandler(object sender, GetliuliangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetliuliangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetliuliangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void fx_liuyucj_sdstateCompletedEventHandler(object sender, fx_liuyucj_sdstateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fx_liuyucj_sdstateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fx_liuyucj_sdstateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void fx_liuyucj_sdmaxCompletedEventHandler(object sender, fx_liuyucj_sdmaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fx_liuyucj_sdmaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fx_liuyucj_sdmaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void fx_liuyucj_stateCompletedEventHandler(object sender, fx_liuyucj_stateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fx_liuyucj_stateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fx_liuyucj_stateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ToStrongCompletedEventHandler(object sender, ToStrongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ToStrongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ToStrongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void fx_liuyujyCompletedEventHandler(object sender, fx_liuyujyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fx_liuyujyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fx_liuyujyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void fx_fenquCompletedEventHandler(object sender, fx_fenquCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fx_fenquCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fx_fenquCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591